-- 1. 게시판 테이블 (GESI)
CREATE TABLE GESI (
    BOARD_NUM NUMBER PRIMARY KEY,
    MEMID VARCHAR2(50),
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);

-- 2. 회원 테이블 (MEM)
CREATE TABLE MEM (
    MEMID VARCHAR2(10) PRIMARY KEY,
    PASS VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    EMAIL VARCHAR2(20) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- 3. 댓글 테이블 (COMMENTS)
CREATE TABLE COMMENTS (
    C_NUM NUMBER PRIMARY KEY,
    BOARD_NUM NUMBER,
    MEMID VARCHAR2(50),
    C_CONTENT VARCHAR2(500),
    REG_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_BOARD FOREIGN KEY (BOARD_NUM) REFERENCES GESI(BOARD_NUM)
);